CREATE TABLE user_dest (
  userDest_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES t_travels_users(id) ON DELETE CASCADE,
  dest_id INTEGER REFERENCES destinations(dest_id) ON DELETE CASCADE,
  goal_date DATE,
  budget DECIMAL(12,2)
);